name: Lint

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lowest: ['0', '1']
        php-versions: ['7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-php${{ matrix.php-versions }}-lowest${{ matrix.lowest }}-{{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      uses: php-actions/composer@v5
      env:
        COMPOSER_PREFER_LOWEST: ${{ matrix.lowest }}
      with:
        command: install
        args: --prefer-dist --no-progress --prefer-stable --no-suggest --verbose
        php_version: ${{ matrix.php-versions }}
        version: 1

    - name: Run lint
      run: make lint
